### ISSUE TITLE
documents.broadcast throws "Keys in query must be sorted at MerkDbStore.getProof"

### ISSUE THREAD

**Issue by dashameter** [dashevo/js-drive#488]
using sdk 3.18.1 on testnet in node

    await platform.documents.broadcast(documentBatch, identity);

throws the following error, thow the documents seem to get store on dpp successfully? 

```
MaxRetriesReachedError: Max retries reached: 13 INTERNAL: Keys in query must be sorted at MerkDbStore.getProof (/usr/src/app/lib/merkDb/MerkDbStore.js:110:20) at DriveClient.request (/usr/src/app/lib/externalApis/drive/DriveClient.js:61:11)
    at GrpcTransport.request (dash-rates/rates/node_modules/@dashevo/dapi-client/lib/transport/GrpcTransport.js:88:15) {
  error: Error: 13 INTERNAL: Keys in query must be sorted at MerkDbStore.getProof (/usr/src/app/lib/merkDb/MerkDbStore.js:110:20) at DriveClient.request (/usr/src/app/lib/externalApis/drive/DriveClient.js:61:11)
      at Object.exports.createStatusError (dash-rates/rates/node_modules/grpc/src/common.js:91:15)
      at Object.onReceiveStatus (dash-rates/rates/node_modules/grpc/src/client_interceptors.js:1209:28)
      at InterceptingListener._callNext (dash-rates/rates/node_modules/grpc/src/client_interceptors.js:568:42)
      at InterceptingListener.onReceiveStatus (dash-rates/rates/node_modules/grpc/src/client_interceptors.js:618:8)
      at InterceptingListener._callNext (dash-rates/rates/node_modules/grpc/src/client_interceptors.js:574:12)
      at InterceptingListener.onReceiveStatus (dash-rates/rates/node_modules/grpc/src/client_interceptors.js:618:8)
      at callback (dash-rates/rates/node_modules/grpc/src/client_interceptors.js:847:24) 

{
    code: 13,
    metadata: Metadata {
      _internal_repr: {
        server: [ 'nginx/1.19.7' ],
        date: [ 'Fri, 26 Mar 2021 10:09:59 GMT' ],
        'content-length': [ '0' ],
        stack: [
          '"Error: Keys in query must be sorted at MerkDbStore.getProof (/usr/src/app/lib/merkDb/MerkDbStore.js:110:20)\\n    at DriveClient.request (/usr/src/app/lib/externalApis/drive/DriveClient.js:61:11)\\n    at runMicrotasks (<anonymous>)\\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\\n    at async fetchProofForStateTransition (/usr/src/app/lib/externalApis/drive/fetchProofForStateTransitionFactory.js:16:36)\\n    at async waitForStateTransitionResultHandler (/usr/src/app/lib/grpcServer/handlers/platform/waitForStateTransitionResultHandlerFactory.js:114:27)\\n    at async rpcMethodErrorHandler (/node_modules/@dashevo/grpc-common/lib/server/error/wrapInErrorHandlerFactory.js:25:24)"'
        ]
      },
      flags: 0
    },
    details: 'Keys in query must be sorted at MerkDbStore.getProof (/usr/src/app/lib/merkDb/MerkDbStore.js:110:20) at DriveClient.request (/usr/src/app/lib/externalApis/drive/DriveClient.js:61:11)'
  }
}
```

To replicate run `node add-rate.js` at https://github.com/dashameter/rates/blob/0.18.1/add-rate.js

**Comment by shumkov** [comment]
Fixed in 0.19 version.
